# ENTITY SERVICES
services:
    digip_reno.service.house:
        class: Digip\RenovationBundle\Service\HouseService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'
            - '@knp_snappy.pdf'
            - '@router'
        calls:
            - [ setUrlHeatMap, ['%digip_reno.gks_url_map_heat%'] ]
            - [ setUrlSolarMap, ['%digip_reno.gks_url_map_solar%'] ]

    digip_reno.service.config:
        class: Digip\RenovationBundle\Service\ConfigService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'

    digip_reno.service.renewables:
        class: Digip\RenovationBundle\Service\RenewablesService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'

    digip_reno.service.buildcost:
        class: Digip\RenovationBundle\Service\BuildCostService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'

    digip_reno.service.parameter:
        class: Digip\RenovationBundle\Service\ParameterService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'

    digip_reno.service.defaults:
        class: Digip\RenovationBundle\Service\DefaultsService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'

    digip_reno.service.content:
        class: Digip\RenovationBundle\Service\ContentService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'

    digip_reno.service.subsidy:
        class: Digip\RenovationBundle\Service\SubsidyService
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'
