parameters:
    digip_reno.gks_url_map_heat: "http://warmtefoto.gent.be/?bb_token=[[BB_TOKEN]]&bb_address=[[BB_ADDRESS]]&returnurl=[[BB_RETURN_URL]]"
    digip_reno.gks_url_map_solar: "http://zonnekaart.gent.be/?bb_token=[[BB_TOKEN]]&bb_address=[[BB_ADDRESS]]&returnurl=[[BB_RETURN_URL]]"

services:
    # EnergyCalculator
    digip_reno.calculator.factory:
        class: Digip\RenovationBundle\Calculator\CalculatorFactory
        calls:
            - [ setContainer, [ '@service_container' ] ]

    # HELPER SERVICES
    digip_reno.service.mailer:
        class: Digip\RenovationBundle\Service\MailService
        arguments:
            - '@mailer'
            - '@templating'
            - '@file_locator'

