imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../vendor/ctrl-f5/ctrl-common/Resources/config/symfony_services_commands.yml }

# parameters

parameters:
    pdo_session.db_options:
        db_table:    session
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time

# framework

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 150504_1
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: session.handler.pdo
    fragments:       ~
    http_method_override: true
    translator: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    # allow the use of non existing variables
    strict_variables: false

    # override default forms to comply with bootstrap formatting
    form:
        resources:
            - "::bootstrap_forms.html.twig"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%use_assetic_controller%"
    bundles:        [ DigipRenovationBundle ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # let doctrine ignore session table
        schema_filter: ~^(?!session)~

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# FOS User bundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Digip\RenovationBundle\Entity\User
    from_email:
        address: info@gentklimaatstad.be
        sender_name: Gent Klimaatstad

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# services

services:
    pdo:
        class: PDO
        arguments:
            dsn:      "mysql:host=%database_host%;dbname=%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
        calls:
            - [setAttribute, [3, 2]] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo_session.db_options%"]

# CKEditor

trsteel_ckeditor:
    startup_outline_blocks: false
    language: 'nl-be'
    # allow the target="_blank" attributes on links
    html_purifier:
        config: { "Attr.AllowedFrameTargets": [ "_blank" ] }

# assetic filters: minifier for JS and CSS
minifier:
    filter:
        name:
            css: minifier_css
            js: minifier_js
