# digipolis renovation bundle routes
digip_renovations_front:
    resource:  '@DigipRenovationBundle/Resources/config/routing/routing.front.yml'

digip_renovations_admin:
    resource: '@DigipRenovationBundle/Resources/config/routing/routing.admin.yml'

# FOS User authentication routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
