admin:
    path:     /admin
    defaults: { _controller: DigipRenovationBundle:Config:index }

admin_matrix:
    path:     /admin/config
    defaults: { _controller: DigipRenovationBundle:Config:index }

admin_matrix_category_percent_update:
    path:     /admin/config-category/percent
    defaults: { _controller: DigipRenovationBundle:Config:updateCategoryPercent }

admin_matrix_transformation_update:
    path:     /admin/config-transformation/{configFrom}/{configTo}/{inverse}
    defaults: { _controller: DigipRenovationBundle:Config:updateConfigTransformation, inverse: false }

admin_config_labels:
    path:     /admin/config-labels
    defaults: { _controller: DigipRenovationBundle:Config:labels }

admin_parameters:
    path:     /admin/parameters
    defaults: { _controller: DigipRenovationBundle:Parameter:index }

admin_parameters_update:
    path:     /admin/parameter/update
    defaults: { _controller: DigipRenovationBundle:Parameter:updateParameters }

admin_renewables:
    path:     /admin/renewables
    defaults: { _controller: DigipRenovationBundle:Renewable:index }

admin_renewables_update:
    path:     /admin/renewables/update
    defaults: { _controller: DigipRenovationBundle:Renewable:updateRenewables }

admin_buildcosts:
    path:     /admin/buildcosts
    defaults: { _controller: DigipRenovationBundle:BuildCost:index }

admin_buildcosts_update:
    path:     /admin/buildcosts/update
    defaults: { _controller: DigipRenovationBundle:BuildCost:updateBuildCosts }

admin_energy:
    path:     /admin/verbruik
    defaults: { _controller: DigipRenovationBundle:DefaultEnergy:index }

admin_energy_update:
    path:     /admin/energy/{id}
    defaults: { _controller: DigipRenovationBundle:DefaultEnergy:updateDefaultEnergy }

admin_surfaces:
    path:     /admin/afmetingen
    defaults: { _controller: DigipRenovationBundle:Defaults:index }

admin_surfaces_update:
    path:     /admin/afmetingen/{id}
    defaults: { _controller: DigipRenovationBundle:Defaults:updateDefaults }

admin_surface_roof_update:
    path:     /admin/afmeting-dak/{id}
    defaults: { _controller: DigipRenovationBundle:Defaults:updateDefaultRoof }

admin_subsidies:
    path:     /admin/subsidies
    defaults: { _controller: DigipRenovationBundle:Subsidy:index }

admin_subsidies_update:
    path:     /admin/subsidies/update
    defaults: { _controller: DigipRenovationBundle:Subsidy:update }

admin_content:
    path:     /admin/content
    defaults: { _controller: DigipRenovationBundle:Content:index }

admin_content_edit:
    path:     /admin/content/edit/{slug}
    defaults: { _controller: DigipRenovationBundle:Content:editBySlug }

admin_houses:
    path:     /admin/houses
    defaults: { _controller: DigipRenovationBundle:House:adminList }

admin_houses_download:
    path:     /admin/houses/download
    defaults: { _controller: DigipRenovationBundle:House:adminListExport }
